{{- include "corpuskit.validate" . -}}
{{- range $component, $name := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  {{- if or (eq $component "migrator") (eq $component "phoible") }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: before-hook-creation
  {{- end }}
  labels:
    {{- include "corpuskit.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component | kebabcase }}
automountServiceAccountToken: false
{{- end }}
